import test from 'node:test';
import assert from 'node:assert/strict';
import { generatePdfBuffer } from '../utils/pdfGenerator';

test('generatePdfBuffer renders a table layout without throwing', async () => {
  const buffer = await generatePdfBuffer({
    title: 'Proposal PROP-2026-0001',
    companyName: 'CrewCam HR Cloud',
    recipientName: 'Acme Inc',
    recipientSubtitle: 'John Smith · john@acme.test',
    lines: [{ label: 'Valid Until', value: '12/31/2026' }],
    table: {
      items: [
        { description: 'Pro Plan (PROFESSIONAL)', amount: '₹5,000' },
        { description: 'Setup Fee', amount: '₹1,000' },
      ],
      totalLabel: 'Total',
      totalValue: '₹6,000',
    },
    preparedBy: 'Jane Admin',
    termsNote: 'Valid for 14 days from issue.',
    footerNote: 'Generated by CrewCam HR Cloud.',
  });

  assert.ok(Buffer.isBuffer(buffer));
  assert.ok(buffer.length > 0);
  assert.equal(buffer.subarray(0, 4).toString('latin1'), '%PDF');
});

test('generatePdfBuffer falls back to plain lines when no table is given', async () => {
  const buffer = await generatePdfBuffer({
    title: 'Quotation QTN-2026-0001',
    lines: [{ label: 'Total', value: '₹1,000' }],
  });

  assert.ok(Buffer.isBuffer(buffer));
  assert.ok(buffer.length > 0);
});
