import { generatePdfBuffer, savePdfToCloudinary } from '../utils/pdfGenerator';
import { Quotation } from '../models/Quotation';
import { Invoice } from '../models/Invoice';

function formatMoney(amount: number, currency: 'INR' | 'USD') {
  const symbol = currency === 'USD' ? '$' : '₹';
  return `${symbol}${amount.toLocaleString('en-IN')}`;
}

export async function generateQuotationNumber(): Promise<string> {
  const year = new Date().getFullYear();
  const count = await Quotation.countDocuments({ quotationNumber: { $regex: `^QTN-${year}-` } });
  return `QTN-${year}-${String(count + 1).padStart(4, '0')}`;
}

export async function generateInvoiceNumber(): Promise<string> {
  const year = new Date().getFullYear();
  const count = await Invoice.countDocuments({ invoiceNumber: { $regex: `^INV-${year}-` } });
  return `INV-${year}-${String(count + 1).padStart(4, '0')}`;
}

export async function buildQuotationPdf(params: {
  quotationNumber: string;
  companyName: string;
  items: { description: string; amount: number }[];
  totalAmount: number;
  currency: 'INR' | 'USD';
  validUntil?: Date;
}): Promise<string> {
  const buffer = await generatePdfBuffer({
    title: `Quotation ${params.quotationNumber}`,
    companyName: 'CrewCam HR Cloud',
    recipientName: params.companyName,
    lines: [
      ...params.items.map((i) => ({ label: i.description, value: formatMoney(i.amount, params.currency) })),
      { label: 'Total', value: formatMoney(params.totalAmount, params.currency) },
      ...(params.validUntil ? [{ label: 'Valid Until', value: params.validUntil.toLocaleDateString() }] : []),
    ],
    footerNote: 'This quotation is generated by CrewCam HR Cloud and is subject to the terms discussed with your account representative.',
  });
  return savePdfToCloudinary(buffer, `${params.quotationNumber}.pdf`);
}

export async function buildInvoicePdf(params: {
  invoiceNumber: string;
  companyName: string;
  type: 'SETUP_FEE' | 'SUBSCRIPTION';
  amount: number;
  discountAmount?: number;
  taxRate?: number;
  taxAmount?: number;
  totalAmount: number;
  amountPaid: number;
  currency: 'INR' | 'USD';
  status: string;
  dueDate?: Date;
}): Promise<string> {
  const buffer = await generatePdfBuffer({
    title: `Invoice ${params.invoiceNumber}`,
    companyName: 'CrewCam HR Cloud',
    recipientName: params.companyName,
    lines: [
      { label: 'Type', value: params.type === 'SETUP_FEE' ? 'One-Time Setup Fee' : 'Subscription' },
      { label: 'Subtotal', value: formatMoney(params.amount, params.currency) },
      ...(params.discountAmount ? [{ label: 'Discount', value: `-${formatMoney(params.discountAmount, params.currency)}` }] : []),
      ...(params.taxAmount ? [{ label: `GST (${params.taxRate}%)`, value: formatMoney(params.taxAmount, params.currency) }] : []),
      { label: 'Total Amount Due', value: formatMoney(params.totalAmount, params.currency) },
      { label: 'Amount Paid', value: formatMoney(params.amountPaid, params.currency) },
      { label: 'Status', value: params.status },
      ...(params.dueDate ? [{ label: 'Due Date', value: params.dueDate.toLocaleDateString() }] : []),
    ],
    footerNote: 'Generated by CrewCam HR Cloud. For payment queries, contact your account representative.',
  });
  return savePdfToCloudinary(buffer, `${params.invoiceNumber}.pdf`);
}
